"""Greedily combine residual tables that transfer across every time split.

This is deliberately conservative: a candidate is accepted only when its
*incremental* Brier gain is non-negative on all four forward-time transfers.
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd

from research_residual_portfolio_v19 import (
    SPECS,
    apply_table,
    build_table,
    prepare,
)


SHRINKS = (100., 200., 400., 800., 1600., 3200., 6400., 12800.)
WEIGHTS = np.arange(.025, .601, .025)


def normalized_gain(target, base, correction):
    uncertainty = float(target.mean() * (1. - target.mean()))
    residual = target - base
    return float(
        100000. * np.mean(2. * residual * correction - correction * correction)
        / uncertainty
    )


def main():
    root = Path(__file__).resolve().parent
    raw = pd.read_csv(
        root / "data/train.csv", encoding="utf-8-sig", low_memory=False,
    )
    rows = {
        year: prepare(raw.loc[raw["season"].eq(year)].reset_index(drop=True))
        for year in (2023, 2024)
    }
    with np.load(root / "outputs/v19_oof_predictions.npz") as loaded:
        oof = {key: loaded[key] for key in loaded.files}
    folds = {}
    for year in (2023, 2024):
        mask = oof["season"] == year
        y = oof["target"][mask].astype(np.float64)
        base = oof["blended"][mask].astype(np.float64)
        folds[year] = {"y": y, "base": base, "residual": y - base}

    m23 = len(rows[2023]) // 2
    m24 = len(rows[2024]) // 2
    blocks = {
        "2023_h2": (rows[2023].iloc[m23:], folds[2023]["y"][m23:],
                    folds[2023]["base"][m23:], "23h1"),
        "2024_h1": (rows[2024].iloc[:m24], folds[2024]["y"][:m24],
                    folds[2024]["base"][:m24], "23"),
        "2024_h2": (rows[2024].iloc[m24:], folds[2024]["y"][m24:],
                    folds[2024]["base"][m24:], "23"),
        "2024_h1_to_h2": (rows[2024].iloc[m24:], folds[2024]["y"][m24:],
                           folds[2024]["base"][m24:], "24h1"),
    }

    # Cache the unweighted correction generated by every frozen table.
    values = {}
    for name, keys in SPECS.items():
        for shrink in SHRINKS:
            tables = {
                "23h1": build_table(rows[2023].iloc[:m23],
                                     folds[2023]["residual"][:m23], keys, shrink),
                "23": build_table(rows[2023], folds[2023]["residual"], keys, shrink),
                "24h1": build_table(rows[2024].iloc[:m24],
                                     folds[2024]["residual"][:m24], keys, shrink),
            }
            for label, (frame, _y, _base, source) in blocks.items():
                value = apply_table(frame, tables[source], keys)
                values[(name, shrink, label)] = np.where(
                    frame["game_type"].eq("R").to_numpy(), value, 0.,
                )

    total = {label: np.zeros(len(block[0]), dtype=np.float64)
             for label, block in blocks.items()}
    gains = {label: 0. for label in blocks}
    remaining = set(SPECS)
    selected = []
    for step in range(8):
        best = None
        for name in remaining:
            for shrink in SHRINKS:
                for weight in WEIGHTS:
                    candidate_gains = {}
                    marginal = {}
                    for label, (_frame, y, base, _source) in blocks.items():
                        correction = total[label] + weight * values[(name, shrink, label)]
                        candidate_gains[label] = normalized_gain(y, base, correction)
                        marginal[label] = candidate_gains[label] - gains[label]
                    # Reject effects that depend on one particular era/split.
                    if min(marginal.values()) < -1e-9:
                        continue
                    rank = (min(candidate_gains.values()),
                            float(np.mean(list(candidate_gains.values()))),
                            min(marginal.values()))
                    if best is None or rank > best[0]:
                        best = (rank, name, shrink, float(weight),
                                candidate_gains, marginal)
        if best is None or min(best[5].values()) < .01:
            break
        _rank, name, shrink, weight, candidate_gains, marginal = best
        for label in blocks:
            total[label] += weight * values[(name, shrink, label)]
        gains = candidate_gains
        remaining.remove(name)
        selected.append({
            "step": step + 1, "name": name, "keys": SPECS[name],
            "shrink": shrink, "weight": weight,
            "marginal_gains": marginal, "total_gains": gains.copy(),
        })
        print(json.dumps(selected[-1], indent=2), flush=True)

    report = {"selected": selected, "final_gains": gains}
    output = root / "research/residual_portfolio_joint_v19.json"
    output.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(json.dumps(report, indent=2), flush=True)
    print(f"Saved {output}", flush=True)


if __name__ == "__main__":
    main()
